version: '3.8'

services:
  app:
    image: basics-docker-lab:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1010

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1010
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: